---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: do_centos-6.5_chef-latest
    driver_config:
      provider: virtualbox
      box: do_centos-6.5_chef-latest
      require_chef_omnibus: true
suites:
  - name: memcached
    run_list:
      - recipe[memcached::testing]
    attributes:
      memcached:
        test: "127.0.0.1"
      platform_family: "redhat"
